### ISSUE TITLE
Feature: Review past week

### ISSUE THREAD

**Issue by George713** [George713/sveltekit-ripped-app#34]
### Current Situation
At the end of the week (Sunday), a progress picture is taken. Nothing else happens.

### Desired Situation
Separately from taking a picture, a review process is started. It includes:
- view at evolution of weight
- option to adjust intake calories
- win state, if goal was reached

### ToDos
- [x] Research graph libraries
- [x] Find formula for smoothed weight
- [x] Design look of screens (figma)
  - [x] Review prompt
  - [x] Weight graph
  - [x] Adjust screen
- [x] Implement look
  - [x] Review prompt
  - [x] Weight graph
  - [x] Adjust screen
- [x] Implement functionality
